# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Elizabeth Vargas
title: Senior Network System Administrator
email: elizabeth.vargas@hw.ac.uk
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
I am currently a Robotics Researcher in Computer Vision for underwater robots. During my Ph.D. I worked on Signal Processing for Acoustic Localisation at Heriot-Watt 
University. I obtained my Master's degree in Computer Vision and Robotics from an Erasmus 
Mundus Master Programm called ViBot, awarded by University of Burgundy, University of Girona 
and Heriot-Watt University and my Bachelor's degree in computer science from Universidad del 
Valle. During my studies, I have also spent time as a summer intern at Toshiba Medical 
Visualization Systems (Jun - Sep 2015), innovation camp participant at Siemens Healthcare GmbH 
(Feb - Apr 2012) and research intern at Philips Technology GmbH Research Laboratories (Mar - Jul 2011). 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
