# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Elizabeth Vargas
title: Research Associate
#institute: Ocean Systems Laboratory
#university: Heriot-Watt University
#office: Earl Mountbatten G.06
#country: Edinburgh, United Kingdom
#email: elizabeth.vargas@hw.ac.uk
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: elizavargasv
#github_username:  evargasv
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
#linkedin_username: evargasv
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a Research Associate at <a href="https://orcahub.org/" target="_blank">ORCA Hub</a> working on computer vision for underwater robots. I obtained my PhD in Signal 
  Processing from <a href="https://www.hw.ac.uk/schools/engineering-physical-sciences/institutes/sensors-signals-systems.htm" target="_blank">Heriot-Watt University</a> and my 
  Master's degree in Computer Vision and Robotics via an Erasmus Mundus Master Programme called <a href="https://www.vibot.org/" target="_blank">VIBOT</a>, awarded by the 
  <a href="https://en.u-bourgogne.fr/" target="_blank">University of Burgundy</a> (France), 
  <a href="http://www.udg.edu/en/" target="_blank">University of Girona</a> (Spain) and 
  <a href="https://www.hw.ac.uk/" target="_blank">Heriot-Watt University</a> (United Kingdom). 
  I received my Bachelor's degree in computer science from 
  <a href="http://eisc.univalle.edu.co/index.php/laboratorios/mmv-lab" target="_blank">Universidad del Valle</a>. During my studies, I have also spent time as a research intern 
  at <a href="https://research.eu.medical.canon/" target="_blank">Toshiba Medical Visualization Systems</a> and 
  <a href="https://www.philips.com/a-w/research/locations/aachen.html" target="_blank">Philips Research Aachen</a>, and participated in an Innovation Think Tank organised by 
  <a href="https://www.siemens-healthineers.com/en-uk/careers/innovation-think-tank" target="_blank">Siemens Healthcare</a>.

  <a href="https://mailhide.io/e/322Ka" target="_blank">Email</a> / 
  <a href="https://www.linkedin.com/in/evargasv/" target="_blank">LinkedIn</a> / 
  <a href="https://scholar.google.com/citations?user=SyDXC-MAAAAJ&hl=en" target="_blank">Google Scholar</a> / 
  <a href="https://github.com/evargasv" target="_blank">Github</a> / 
  <a href="https://twitter.com/elizavargasv" target="_blank">Twitter</a> / 
  <a href="cv/vargas_cv.pdf" target="_blank">CV</a>

# News Section
more_title: News
more_content: | # this will include new lines to allow paragraphs
  <table>
  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Feb. 2020:</b></td>
      <td>I am one of the organisers of the <a href="https://sites.google.com/view/wicvworkshop-eccv2020/" target="_blank">WiCV</a> workshop to be 
  held in conjunction with <a href="https://eccv2020.eu/" target="_blank">ECCV 2020</a> in Glasgow, United Kingdom.</td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Jan. 2020:</b></td>
      <td>Our abstract Image Enhancement for Underwater 3D Mapping has been accepted to 
  <a href="https://singapore20.oceansconference.org/" target="_blank">OCEANS 2020</a>.</td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Nov. 2019:</b></td>
      <td>I defended my PhD thesis, titled <a href="publications/theses/vargas2020_phd.pdf" target="_blank">Acoustic Source Localisation in Constrained Environments</a>. 
  Examiners: <a href="https://sites.google.com/site/abderrahimhalimi/" target="_blank">Abderrahim Halimi</a> (Heriot-Watt University) 
  and <a href="https://www.southampton.ac.uk/engineering/about/staff/krh.page" target="_blank">Keith Holland</a> (University of Southampton). 
  Slides <a href="publications/theses/vargas2020_phd_slides.pdf" target="_blank">here</a>.</td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Oct. 2019:</b></td>
      <td>I participated in the third <a href="https://orcahub.org/" target="_blank">ORCA Hub</a> demonstrations. 
  Press release <a href="https://orcahub.org/articles/a-summary-of-the-blyth-capability-demonstrations" target="_blank">here</a>.</td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Jan. 2019:</b></td>
      <td>I joined the <a href="https://orcahub.org/" target="_blank">ORCA Hub</a> as a Research Associate, and member of the 
  <a href="http://pro.hw.ac.uk/" target="_blank">Perception and RObotics (PRO)</a> group.</td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Jul. 2018:</b></td>
      <td>I attended the <a href="http://grammars.grlmc.com/DeepLearn2018/" target="_blank">2<sup>nd</sup> International Summer School on Deep Learning 2018</a> 
  in Genoa, Italy.</td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>May. 2018:</b></td>
      <td>Our paper <a href="publications/conferences/vargas2018_eusipco.pdf" target="_blank">A Compressed Encoding Scheme for Approximate TDOA Estimation</a> has been
  accepted to <a href="http://www.eusipco2018.org/" target="_blank">EUSIPCO 2018</a>.</td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Apr. 2018:</b></td>
      <td>I was a student helper in the <a href="https://robotical.io/" target="_blank">Marty: Activate!</a> workshop, as part of the 
  <a href="https://www.sciencefestival.co.uk/" target="_blank">Edinburgh Science Festival</a>.  </td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Jan. 2018:</b></td>
      <td>Our paper <a href="publications/conferences/vargas2018_icassp.pdf" target="_blank">Impact of Microphone Array Configurations on Acoustic Localization</a> has been 
      accepted to <a href="https://2018.ieeeicassp.org/" target="_blank">ICASSP 2018</a>.</td>
  </tr>

  <tr>
      <td style="width:89px;text-align-last:justify;padding-right:10px"><b>Jan. 2018:</b></td>
      <td>I volunteered as robot game judge at <a href="https://education.theiet.org/first-lego-league-programmes/" target="_blank">The FIRST&#174; LEGO&#174; League</a>
  in Edinburgh, United Kingdom.</td>
  </tr>

  </table>

# - **Feb. 2020:** I am one of the organisers of the <a href="https://sites.google.com/view/wicvworkshop-eccv2020/" target="_blank">WiCV</a> workshop to be 
# held in conjunction with <a href="https://eccv2020.eu/" target="_blank">ECCV 2020</a> in Glasgow, United Kingdom.
# - **Jan. 2020:** Our abstract Image Enhancement for Underwater 3D Mapping has been accepted to 
# <a href="https://singapore20.oceansconference.org/" target="_blank">OCEANS 2020</a>.
# - **Nov. 2019:** I defended my PhD thesis, titled <a href="publications/theses/vargas2020_phd.pdf" target="_blank">Acoustic Source Localisation in Constrained Environments</a>. 
# Examiners: <a href="https://sites.google.com/site/abderrahimhalimi/" target="_blank">Abderrahim Halimi</a> (Heriot-Watt University) 
# and <a href="https://www.southampton.ac.uk/engineering/about/staff/krh.page" target="_blank">Keith Holland</a> (University of Southampton). 
# Slides <a href="publications/theses/vargas2020_phd_slides.pdf" target="_blank">here</a>.
# - **Oct. 2019:** I participated in the third <a href="https://orcahub.org/" target="_blank">ORCA Hub</a> demonstrations. 
# Press release <a href="https://orcahub.org/articles/a-summary-of-the-blyth-capability-demonstrations" target="_blank">here</a>.
# - **Jan. 2019:** I joined the <a href="https://orcahub.org/" target="_blank">ORCA Hub</a> as a Research Associate, and member of the 
# <a href="http://pro.hw.ac.uk/" target="_blank">Perception and RObotics (PRO)</a> group. 
# - **Jul. 2018:** I attended the <a href="http://grammars.grlmc.com/DeepLearn2018/" target="_blank">2<sup>nd</sup> International Summer School on Deep Learning 2018</a> 
# in Genoa, Italy.
# - **May. 2018:** Our paper <a href="publications/conferences/vargas2018_eusipco.pdf" target="_blank">A Compressed Encoding Scheme for Approximate TDOA Estimation</a> has been
# accepted to <a href="http://www.eusipco2018.org/" target="_blank">EUSIPCO 2018</a>.
# - **Apr. 2018:** I was a student helper in the <a href="https://robotical.io/" target="_blank">Marty: Activate!</a> workshop, as part of the 
# <a href="https://www.sciencefestival.co.uk/" target="_blank">Edinburgh Science Festival</a>.  
# - **Jan. 2018:** Our paper <a href="publications/conferences/vargas2018_icassp.pdf" target="_blank">Impact of Microphone Array Configurations on Acoustic Localization</a> has been accepted to <a href="https://2018.ieeeicassp.org/" target="_blank">ICASSP 2018</a>.
# - **Jan. 2018:** I volunteered as robot game judge at <a href="https://education.theiet.org/first-lego-league-programmes/" target="_blank">The FIRST&#174; LEGO&#174; League</a>
# in Edinburgh, United Kingdom. 

# Timeline Section
# experience_title: Experience and Education
# experience_content: | # this will include new lines to allow paragraphs

#   - **2019-Present:** <font color="#2F4F4F"><b>Research Associate.</b></font> 
#   <a href="https://orcahub.org/" target="_blank">ORCA Hub</a>. Mapping, surveying and inspection.
#   - **2015-2019:** <font color="#2F4F4F"><b>PhD Signal Processing.</b></font> 
#   <a href="https://www.hw.ac.uk/schools/engineering-physical-sciences/institutes/sensors-signals-systems.htm" target="_blank">Heriot-Watt University</a>. 
#   Advisors: <a href="https://researchportal.hw.ac.uk/en/persons/keith-edgar-brown" target="_blank">Keith Brown</a> and 
#   <a href="http://homepages.inf.ed.ac.uk/ksubr/" target="_blank">Kartic Subr</a>.  
#   - **2013-2015:** <font color="#2F4F4F"><b>MSc Computer Vision and Robotics.</b></font> 
#   <a href="https://www.vibot.org/" target="_blank">Erasmus Mundus Masters in Vision and Robotics</a>. 
#   Advisor: <a href="https://scholar.google.co.uk/citations?hl=en&user=54HbSNQAAAAJ&view_op=list_works&sortby=pubdate" target="_blank">Keith Goatman</a>.
#   - **Summer 2015:** <font color="#2F4F4F"><b>Research Intern.</b></font> 
#   <a href="https://research.eu.medical.canon/" target="_blank">Toshiba Medical Visualization Systems</a>. 
#   Advisor: <a href="https://scholar.google.com/citations?hl=en&user=F3t43XcAAAAJ&view_op=list_works&sortby=pubdate" target="_blank">Corn&#233; Hoogendoorn</a>.
#   - **2012-2013:** <font color="#2F4F4F"><b>Project Engineer.</b></font> 
#   <a href="https://www.ivu.com/" target="_blank">IVU Traffic Technologies</a>.
#   - **2006-2012:** <font color="#2F4F4F"><b>BSc Computer Science.</b></font> 
#   <a href="http://eisc.univalle.edu.co/index.php/laboratorios/mmv-lab" target="_blank">Universidad del Valle</a>. 
#   Advisor: <a href="http://eisc.univalle.edu.co/index.php/la-escuela/profesores/maria-patricia-trujillo-uribe" target="_blank">Mar&#237;a Trujillo</a>.
#   - **Spring 2012:** <font color="#2F4F4F"><b>Innovation Think Tank Participant.</b></font>
#   <a href="https://www.siemens-healthineers.com/en-uk/careers/innovation-think-tank" target="_blank">Siemens Healthcare</a>.
#   - **Spring 2011:** <font color="#2F4F4F"><b>Research Intern.</b></font> 
#   <a href="https://www.philips.com/a-w/research/locations/aachen.html" target="_blank">Philips Research Aachen</a>. 
#   Advisor: <a href="https://www.linkedin.com/in/martin-weibrecht-8b133723/" target="_blank">Martin Weibrecht</a>.
#   - **2010-2011:** <font color="#2F4F4F"><b>BSc Exchange Student.</b></font>
#   <a href="https://www.informatik.uni-erlangen.de/department/" target="_blank">Friedrich-Alexander-Universit&#228;t Erlangen-N&#252;rnberg</a>. 

# Publications Section
projects_title: Publications
projects_content: | # this will include new lines to allow paragraphs

  <font size="4"><b>Conferences</b></font>

  - **E. Vargas**, 
  <a href="https://www.research.ed.ac.uk/portal/en/persons/james-hopgood(c362f445-56b9-44da-b350-c9b32f9f762e)/cv.html?id=10175408" target="_blank">J. R. Hopgood</a>, 
  <a href="https://researchportal.hw.ac.uk/en/persons/keith-edgar-brown" target="_blank">K. Brown</a>, 
  <a href="http://homepages.inf.ed.ac.uk/ksubr/" target="_blank">K. Subr</a>, 
  A Compressed Encoding Scheme for Approximate TDOA Estimation, in European Signal Processing Conference **(EUSIPCO)**, 
  Rome, Italy, September 2018. 
  <a href="publications/conferences/vargas2018_eusipco.pdf" target="_blank">[pdf]</a>
  <a href="publications/conferences/vargas2018_eusipco.bib">[bib]</a>
  <a href="publications/conferences/vargas2018_eusipco_slides.pdf" target="_blank">[slides]</a>

  - **E. Vargas**, 
  <a href="https://researchportal.hw.ac.uk/en/persons/keith-edgar-brown" target="_blank">K. Brown</a>, 
  <a href="http://homepages.inf.ed.ac.uk/ksubr/" target="_blank">K. Subr</a>, 
  Impact of Microphone Array Configurations on Robust 
  Indirect 3D Acoustic Source Localization, in International Conference on Acoustics, 
  Speech and Signal Processing **(ICASSP)**, Calgary, Canada, April 2018.
  <a href="publications/conferences/vargas2018_icassp.pdf" target="_blank">[pdf]</a> 
  <a href="publications/conferences/vargas2018_icassp.bib">[bib]</a>
  <a href="publications/conferences/vargas2018_icassp_slides.pdf" target="_blank">[slides]</a> 

  - C. Bustos, **E. Vargas**, 
  <a href="http://eisc.univalle.edu.co/index.php/la-escuela/profesores/maria-patricia-trujillo-uribe" target="_blank">M. Trujillo</a>, 
  Classifying Estimated Stereo Correspondences 
  based on Delaunay Triangulation, in IberoAmerican Congress on Pattern Recognition 
  **(CIARP)**, Lima, Peru, November 2016.
  <a href="publications/conferences/bustos2016_ciarp.pdf" target="_blank">[pdf]</a> 
  <a href="publications/conferences/bustos2016_ciarp.bib">[bib]</a>

  - **E. Vargas**, 
  <a href="http://eisc.univalle.edu.co/index.php/la-escuela/profesores/maria-patricia-trujillo-uribe" target="_blank">M. Trujillo</a>, 
  A Corresponding Points Classification Approach by Delaunay 
  Triangulation, in Latin American Conference on Networked and Electronic Media 
  **(LACNEM)**, Santiago, Chile, October 2012.
  <a href="publications/conferences/vargas2012_lacnem.pdf" target="_blank">[pdf]</a> 
  <a href="publications/conferences/vargas2012_lacnem.bib">[bib]</a>

  <font size="4"><b>Theses</b></font>

  - **E. Vargas**, Acoustic Source Localisation in Constrained Environments, PhD Thesis, 
  Heriot-Watt University, Edinburgh, United Kingdom, February 2020. 
  <a href="publications/theses/vargas2020_phd.pdf" target="_blank">[pdf]</a> 
  <a href="publications/theses/vargas2020_phd.bib">[bib]</a> 
  <a href="publications/theses/vargas2020_phd_slides.pdf" target="_blank">[slides]</a> 

  - **E. Vargas**, Texture Enhanced Tissue Analysis, MSc Thesis, Erasmus Mundus Masters in 
  Vision and Robotics, Edinburgh, United Kingdom, June 2015.
  <a href="publications/theses/vargas2015_msc.pdf" target="_blank">[pdf]</a> 
  <a href="publications/theses/vargas2015_msc.bib">[bib]</a> 
  <a href="publications/theses/vargas2015_msc_slides.pdf" target="_blank">[slides]</a>

  - **E. Vargas**, Classifying Estimated Corresponding Points by Delaunay Triangulation, 
  BSc Thesis, Universidad del Valle, Cali, Colombia, June 2012.
  <a href="publications/theses/vargas2012_bsc.pdf" target="_blank">[pdf]</a> 
  <a href="publications/theses/vargas2012_bsc.bib">[bib]</a> 
  <a href="publications/theses/vargas2012_bsc_slides.pdf" target="_blank">[slides]</a>

# Footer
footer_show_references: true

# Build settings
remote_theme: evargasv/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
