# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Elizabeth Vargas
title: Research Associate
email: elizabeth.vargas@hw.ac.uk
#website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: elizavargasv
github_username:  evargasv
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: evargasv
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a robotics researcher at Heriot-Watt University.

  I obtained my PhD from Heriot-Watt University.

# Publications Section
projects_title: Publications
projects_content: | # this will include new lines to allow paragraphs

  <h3>Conferences<h3>

  - EUSIPCO

  **Theses**

  - PhD thesis

# Timeline Section
experience_title: Timeline
experience_content: | # this will include new lines to allow paragraphs

  - **2019 - Present:** Research Associate. [ORCAHub](https://orcahub.org/).
  - **2015 - 2019:** PhD Signal Processing. Heriot-Watt University. Advisors: Keith Brown and Kartic Subr.  
  - **2013 - 2015:** MSc Computer Vision and Robotics. Erasmus Mundus Master Program in Computer Vision and Robotics (ViBot).
  - **Summer 2015:** Research Intern. Toshiba Medical Visualization Systems. Advisor: 
  - **2006 - 2012:** BSc in Computer Science. Universidad del Valle. Advisor: 
  - **Spring 2012:** Innovation Camp Participant. Siemens Healthcare.
  - **Spring 2011:** Research Intern. Philips. Advisor: 
  - **2010 - 2011:** BSc Exchange Student. Friedrich-Alexander-Universitat Erlangen-Nurnberg. 

# News Section
more_title: News
more_content: | # this will include new lines to allow paragraphs
  - **Jan. 2020:** I am one of the organizers of the [Women in Computer Vision Workshop](https://sites.google.com/view/wicvworkshop-eccv2020/).
  - **Nov. 2019:** Sucessfully defended my PhD thesis.
  - **Jan. 2019:** Started working for ORCA.

# Footer
footer_show_references: true

# Build settings
remote_theme: evargasv/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
