# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Elizabeth Vargas
title: Research Associate
email: elizabeth.vargas@hw.ac.uk
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: elizavargasv
#github_username:  evargasv
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
#linkedin_username: evargasv
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a Research Associate at [ORCA Hub](https://orcahub.org/) working on computer vision for underwater robots. I obtained my PhD in Signal Processing from 
  [Heriot-Watt University](https://www.hw.ac.uk/schools/engineering-physical-sciences/institutes/sensors-signals-systems.htm) and my Master's degree in Computer Vision and Robotics from an Erasmus Mundus 
  Master Programm called [ViBot](https://www.vibot.org/), awarded by *University of Burgundy*, *University of Girona* and *Heriot-Watt University*. I received my 
  Bachelor's degree in computer science from [Universidad del Valle](http://eisc.univalle.edu.co/index.php/laboratorios/mmv-lab). During my studies, I have also spent time as a research intern at 
  [Toshiba Medical Visualization Systems](https://research.eu.medical.canon/) and [Philips Research Aachen](https://www.philips.com/a-w/research/locations/aachen.html).


  [LinkedIn](https://www.linkedin.com/in/evargasv/) / [Google Scholar](https://scholar.google.com/citations?user=SyDXC-MAAAAJ&hl=en) / 
  [Github](https://github.com/evargasv) / [Twitter](https://twitter.com/elizavargasv) / CV

# News Section
more_title: News
more_content: | # this will include new lines to allow paragraphs
  - **Feb. 2020:** I am one of the organizers of the [Women in Computer Vision Workshop](https://sites.google.com/view/wicvworkshop-eccv2020/) to be held in conjunction with [ECCV](https://eccv2020.eu/) 
  in Glasgow, United Kingdom.
  - **Jan. 2020:** Our abstract *Smart Underwater Vision: Image Enhancement forUnderwater 3D Mapping in the Challenging Environment* was accepted to [OCEANS](https://singapore20.oceansconference.org/).
  - **Nov. 2019:** I defended my Phd thesis, titled Acoustic Source Localisation in Constrained Environments. Examiners: [Abderrahim Halimi](https://sites.google.com/site/abderrahimhalimi/) (Heriot-Watt University) 
  and [Keith Holland](https://www.southampton.ac.uk/engineering/about/staff/krh.page) (University of Southampton). Slides here.
  - **Oct. 2019:** I participated in the third [ORCA Hub](https://orcahub.org/) demonstrations. Press release [here](https://orcahub.org/articles/a-summary-of-the-blyth-capability-demonstrations).
  - **Jan. 2019:** I joined [ORCA Hub](https://orcahub.org/) as Research Associate.

# Timeline Section
experience_title: Timeline
experience_content: | # this will include new lines to allow paragraphs

  - **2019-Now:** *Research Associate.* [ORCA Hub](https://orcahub.org/).
  - **2015-2019:** *PhD Signal Processing.* Heriot-Watt University. Advisors: Keith Brown and Kartic Subr.  
  - **2013-2015:** *MSc Computer Vision and Robotics.* Erasmus Mundus Master Program in Computer Vision and Robotics (ViBot). Advisor: Keith Goatman.
  - **Summer 2015:** *Research Intern.* Toshiba Medical Visualization Systems. Advisor: Corne Hoogendoorn.
  - **2006-2012:** *BSc in Computer Science.* Universidad del Valle. Advisor: Maria Trujillo.
  - **Spring 2012:** *Innovation Camp Participant.* Siemens Healthcare. Advisor: Sultan Haider.
  - **Spring 2011:** *Research Intern.* Philips. Advisor: Martin Weibrecht.
  - **2010-2011:** *BSc Exchange Student.* Friedrich-Alexander-Universitat Erlangen-Nurnberg. 

# Publications Section
projects_title: Publications
projects_content: | # this will include new lines to allow paragraphs

  **Conferences**

  - **E. Vargas**, J. R. Hopgood, K. Brown, K. Subr, A Compressed Encoding Scheme for 
  Approximate TDOA Estimation, in *European Signal Processing Conference*, **(EUSIPCO)**, 
  Rome, Italy, September 2018. ***(Oral Presentation)***

  - **E. Vargas**, K. Brown, K. Subr, Impact of Microphone Array Configurations on Robust 
  Indirect 3D Acoustic Source Localization, in *International Conference on Acoustics, 
  Speech and Signal Processing* **(ICASSP)**, Calgary, Canada, April 2018. 
  ***(Oral Presentation)***

  - C. Bustos, **E. Vargas**, M. Trujillo, Classifying Estimated Stereo Correspondences 
  based on Delaunay Triangulation, in *IberoAmerican Congress on Pattern Recognition*, 
  **(CIARP)**, Lima, Peru, November 2016. 

  - **E. Vargas**, M. Trujillo, A Corresponding Points Classification Approach by Delaunay 
  Triangulation, in *Latin American Conference on Networked and Electronic Media*, 
  **(LACNEM)**, Santiago, Chile, October 2012.

  **Theses**

  - **E. Vargas**, Acoustic Source Localisation in Constrained Environments, *PhD Thesis*, 
  Heriot-Watt University, Edinburgh, United Kingdom, February 2020.

  - **E. Vargas**, Texture Enhanced Tissue Analysis, *MSc Thesis*, Erasmus Mundus Master 
  Program in Computer Vision and Robotics (ViBot), Edinburgh, United Kingdom, June 2015.

  - **E. Vargas**, Classifying Estimated Corresponding Points by Delaunay Triangulation, 
  *BSc Thesis*, Universidad del Valle, Cali, Colombia, June 2012.

# Footer
footer_show_references: true

# Build settings
remote_theme: evargasv/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
