# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Elizabeth Vargas
title: Senior Software Engineer

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a Senior Software Engineer at <a href="https://www.leapautomation.co.uk/" target="_blank">Leap Automation</a>. Previously, I worked
  at <a href="https://ouster.com/" target="_blank">Ouster</a> as a Software Engineer and at <a href="https://orcahub.org/" target="_blank">ORCA Hub</a>
  as a Research Associate. I obtained my PhD in Signal 
  Processing from <a href="https://www.hw.ac.uk/schools/engineering-physical-sciences/institutes/sensors-signals-systems.htm" target="_blank">Heriot-Watt University</a> and my 
  Master's degree in Computer Vision and Robotics via an Erasmus Mundus Master Programme called <a href="https://www.vibot.org/" target="_blank">VIBOT</a>, awarded by the 
  <a href="https://en.u-bourgogne.fr/" target="_blank">University of Burgundy</a> *(France)*, 
  <a href="http://www.udg.edu/en/" target="_blank">University of Girona</a> *(Spain)* and 
  <a href="https://www.hw.ac.uk/" target="_blank">Heriot-Watt University</a> *(United Kingdom)*. 
  I received my Bachelor's degree in computer science from 
  <a href="http://eisc.univalle.edu.co/index.php/laboratorios/mmv-lab" target="_blank">Universidad del Valle</a> *(Colombia)*, during which I participated in an academic
  exchange with the <a href="https://www.fau.eu/" target="_blank">Friedrich–Alexander University Erlangen–N&uuml;rnberg</a> *(Germany)*. 
  I have also spent time as a research intern at 
  <a href="https://research.eu.medical.canon/" target="_blank">Toshiba Medical Visualization Systems</a> and 
  <a href="https://www.philips.com/a-w/research/locations/aachen.html" target="_blank">Philips Research Aachen</a>, and participated in an Innovation Think Tank organised by 
  <a href="https://www.siemens-healthineers.com/en-uk/careers/innovation-think-tank" target="_blank">Siemens Healthcare</a>.

  <center>
  <a href="https://mailhide.io/e/4ScnnHL9" target="_blank">Email</a> /
  <a href="https://www.linkedin.com/in/evargasv/" target="_blank">LinkedIn</a> / 
  <a href="https://scholar.google.com/citations?user=SyDXC-MAAAAJ&hl=en" target="_blank">Google Scholar</a> / 
  <a href="https://github.com/evargasv" target="_blank">Github</a> / 
  <a href="cv/vargas_cv.pdf" target="_blank">CV</a>
  </center>

# News Section
more_title: News
more_content: | # this will include new lines to allow paragraphs
  <table>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Jan. 2023:</b></li></ul></td>
      <td>I joined <a href="https://www.leapautomation.co.uk/" target="_blank">Leap Automation</a> as a Senior Software Engineer, using computer vision to streamline product packing.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Oct. 2021:</b></li></ul></td>
      <td>Following the acquisition of <a href="https://techcrunch.com/2021/10/05/lidar-developer-ouster-agrees-to-buy-sense-photonics-as-it-takes-aim-at-the-auto-industry/" 
      target="_blank">Sense Photonics</a>, I joined <a href="https://ouster.com/industry/automotive/" target="_blank">Ouster</a> in building lidar for the automotive
      industry.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Jul. 2021:</b></li></ul></td>
      <td>Our paper <a href="publications/preprints/luczynski2021arxiv.pdf" target="_blank">Underwater Inspection and Intervention Dataset</a> is now
      available to download as a preprint.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Feb. 2021:</b></li></ul></td>
      <td>Our paper <a href="publications/conferences/vargas2021_icra.pdf" target="_blank">Robust Underwater Visual SLAM Fusing Acoustic Sensing</a> was 
      accepted to <a href="http://www.icra2021.org/" target="_blank">ICRA 2021</a> in Xi’an, China.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Dec. 2020:</b></li></ul></td>
      <td>Our paper <a href="publications/journals/vargas2021_taslp.pdf" target="_blank">On Improved Training of CNN for Acoustic Source Localisation</a> has been
  accepted to <a href="https://signalprocessingsociety.org/publications-resources/ieeeacm-transactions-audio-speech-and-language-processing" target="_blank">TASLP</a>.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Dec. 2020:</b></li></ul></td>
      <td>I joined <a href="https://sensephotonics.com/" target="_blank">Sense Photonics</a> as a Software Engineer, building intelligent 3D vision systems at low-cost.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Feb. 2020:</b></li></ul></td>
      <td>I am co-organising the <a href="https://sites.google.com/view/wicvworkshop-eccv2020/" target="_blank">WiCV</a> workshop to be 
  held in conjunction with <a href="https://eccv2020.eu/" target="_blank">ECCV 2020</a> in Glasgow, United Kingdom.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Nov. 2019:</b></li></ul></td>
      <td>I defended my PhD thesis, <a href="publications/theses/vargas2020_phd.pdf" target="_blank">Acoustic Source Localisation in Constrained Environments</a>. 
  Examiners: <a href="https://sites.google.com/site/abderrahimhalimi/" target="_blank">Abderrahim Halimi</a> (Heriot-Watt University) 
  and <a href="https://www.southampton.ac.uk/engineering/about/staff/krh.page" target="_blank">Keith Holland</a> (University of Southampton). 
  Slides can be found <a href="publications/theses/vargas2020_phd_slides.pdf" target="_blank">here</a>.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Oct. 2019:</b></li></ul></td>
      <td>I participated in the third <a href="https://orcahub.org/" target="_blank">ORCA Hub</a> demonstrations in Blyth, Northumberland. 
  Press release can be found <a href="https://orcahub.org/articles/a-summary-of-the-blyth-capability-demonstrations" target="_blank">here</a>.</td>
  </tr>

  <tr>
      <td style="width:125px;text-align-last:justify;padding-right:5px"><ul style="margin-bottom:0"><li><b>Jan. 2019:</b></li></ul></td>
      <td>I joined the <a href="https://orcahub.org/" target="_blank">ORCA Hub</a> as a Research Associate, and as member of the 
  <a href="http://pro.hw.ac.uk/" target="_blank">Perception and RObotics (PRO)</a> group.</td>
  </tr>

  </table>

# Publications Section
projects_title: Publications
projects_content: | # this will include new lines to allow paragraphs

  <font size="4"><b>Journals</b></font>

  - **E. Vargas**, 
  <a href="https://www.research.ed.ac.uk/portal/en/persons/james-hopgood(c362f445-56b9-44da-b350-c9b32f9f762e)/cv.html?id=10175408" target="_blank">J. R. Hopgood</a>, 
  <a href="https://researchportal.hw.ac.uk/en/persons/keith-edgar-brown" target="_blank">K. Brown</a>, 
  <a href="http://homepages.inf.ed.ac.uk/ksubr/" target="_blank">K. Subr</a>, 
  On Improved Training of CNN for Acoustic Source Localisation, in Transactions on Audio, Speech, and Language Processing **(TASLP)**, 
  January 2021. 
  <a href="publications/journals/vargas2021_taslp.pdf" target="_blank">[pdf]</a>
  <a href="publications/journals/vargas2021_taslp.bib">[bib]</a>
  <a href="https://ieeexplore.ieee.org/document/9316801" target="_blank">[doi]</a>

  <font size="4"><b>Conferences</b></font>

    - **E. Vargas**, 
  <a href="https://scholar.google.com/citations?user=Y_ntBSUAAAAJ&hl=en&oi=ao" target="_blank">R. Scona</a>,
  <a href="https://scholar.google.com/citations?user=tw79vacAAAAJ&hl=en" target="_blank">J. Scharff Wilners</a>, 
  <a href="https://scholar.google.com/citations?user=lwHwxdUAAAAJ&hl=en&oi=ao" target="_blank">T. Luczynski</a>, 
  <a href="https://www.tsaoyu.com/" target="_blank">Y. Cao</a>, 
  <a href="https://researchportal.hw.ac.uk/en/persons/sen-wang" target="_blank">S. Wang</a>, 
  <a href="https://researchportal.hw.ac.uk/en/persons/yvan-petillot" target="_blank">Y. Petillot</a>, 
  Robust Underwater Visual SLAM Fusing Acoustic Sensing, in International Conference on Robotics and Automation **(ICRA)**, 
  Xi'an, China, June 2021. 
  <a href="publications/conferences/vargas2021_icra.pdf" target="_blank">[pdf]</a>
  <a href="publications/conferences/vargas2021_icra.bib">[bib]</a>
  <a href="https://www.youtube.com/watch?v=1V77WicHVCk&ab_channel=ElizabethVargas" target="_blank">[video]</a>


  - **E. Vargas**, 
  <a href="https://www.research.ed.ac.uk/portal/en/persons/james-hopgood(c362f445-56b9-44da-b350-c9b32f9f762e)/cv.html?id=10175408" target="_blank">J. R. Hopgood</a>, 
  <a href="https://researchportal.hw.ac.uk/en/persons/keith-edgar-brown" target="_blank">K. Brown</a>, 
  <a href="http://homepages.inf.ed.ac.uk/ksubr/" target="_blank">K. Subr</a>, 
  A Compressed Encoding Scheme for Approximate TDOA Estimation, in European Signal Processing Conference **(EUSIPCO)**, 
  Rome, Italy, September 2018. 
  <a href="publications/conferences/vargas2018_eusipco.pdf" target="_blank">[pdf]</a>
  <a href="publications/conferences/vargas2018_eusipco.bib">[bib]</a>
  <a href="publications/conferences/vargas2018_eusipco_slides.pdf" target="_blank">[slides]</a>

  - **E. Vargas**, 
  <a href="https://researchportal.hw.ac.uk/en/persons/keith-edgar-brown" target="_blank">K. Brown</a>, 
  <a href="http://homepages.inf.ed.ac.uk/ksubr/" target="_blank">K. Subr</a>, 
  Impact of Microphone Array Configurations on Acoustic Source Localization, in International Conference on Acoustics, 
  Speech and Signal Processing **(ICASSP)**, Calgary, Canada, April 2018.
  <a href="publications/conferences/vargas2018_icassp.pdf" target="_blank">[pdf]</a> 
  <a href="publications/conferences/vargas2018_icassp.bib">[bib]</a>
  <a href="publications/conferences/vargas2018_icassp_slides.pdf" target="_blank">[slides]</a> 

  - <a href="https://scholar.google.com/citations?user=zGRtcyoAAAAJ&hl=en" target="_blank">C. Bustos</a>, 
  **E. Vargas**, 
  <a href="http://eisc.univalle.edu.co/index.php/la-escuela/profesores/maria-patricia-trujillo-uribe" target="_blank">M. Trujillo</a>, 
  Classifying Estimated Stereo Correspondences 
  based on Delaunay Triangulation, in IberoAmerican Congress on Pattern Recognition 
  **(CIARP)**, Lima, Peru, November 2016.
  <a href="publications/conferences/bustos2016_ciarp.pdf" target="_blank">[pdf]</a> 
  <a href="publications/conferences/bustos2016_ciarp.bib">[bib]</a>

  - **E. Vargas**, 
  <a href="http://eisc.univalle.edu.co/index.php/la-escuela/profesores/maria-patricia-trujillo-uribe" target="_blank">M. Trujillo</a>, 
  A Corresponding Points Classification Approach by Delaunay 
  Triangulation, in Latin American Conference on Networked and Electronic Media 
  **(LACNEM)**, Santiago, Chile, October 2012.
  <a href="publications/conferences/vargas2012_lacnem.pdf" target="_blank">[pdf]</a> 
  <a href="publications/conferences/vargas2012_lacnem.bib">[bib]</a>


  <font size="4"><b>Preprints</b></font>

  - <a href="https://scholar.google.com/citations?user=lwHwxdUAAAAJ&hl=en&oi=ao" target="_blank">T. Luczynski</a>,
  <a href="https://scholar.google.com/citations?user=tw79vacAAAAJ&hl=en" target="_blank">J. Scharff Wilners</a>, 
  **E. Vargas**,
  <a href="https://scholar.google.com/citations?user=GovtFqIAAAAJ&hl=en" target="_blank">J. Roe</a>,
  S. Xu,
  <a href="https://www.tsaoyu.com/" target="_blank">Y. Cao</a>, 
  <a href="https://researchportal.hw.ac.uk/en/persons/sen-wang" target="_blank">S. Wang</a>, 
  <a href="https://researchportal.hw.ac.uk/en/persons/yvan-petillot" target="_blank">Y. Petillot</a>, 
  Underwater Inspection and Intervention Dataset, in **arXiv**, July 2021.
  <a href="publications/preprints/luczynski2021arxiv.pdf" target="_blank">[pdf]</a> 
  <a href="publications/preprints/luczynski2021arxiv.bib">[bib]</a>

  <font size="4"><b>Theses</b></font>

  - **E. Vargas**, Acoustic Source Localisation in Constrained Environments, PhD Thesis, 
  Heriot-Watt University, Edinburgh, United Kingdom, February 2020. 
  <a href="publications/theses/vargas2020_phd.pdf" target="_blank">[pdf]</a> 
  <a href="publications/theses/vargas2020_phd.bib">[bib]</a> 
  <a href="publications/theses/vargas2020_phd_slides.pdf" target="_blank">[slides]</a> 

  - **E. Vargas**, Texture Enhanced Tissue Analysis, MSc Thesis, Erasmus Mundus Masters in 
  Vision and Robotics, Edinburgh, United Kingdom, June 2015.
  <a href="publications/theses/vargas2015_msc.pdf" target="_blank">[pdf]</a> 
  <a href="publications/theses/vargas2015_msc.bib">[bib]</a> 
  <a href="publications/theses/vargas2015_msc_slides.pdf" target="_blank">[slides]</a>

  - **E. Vargas**, Classifying Estimated Corresponding Points by Delaunay Triangulation, 
  BSc Thesis, Universidad del Valle, Cali, Colombia, June 2012.
  <a href="publications/theses/vargas2012_bsc.pdf" target="_blank">[pdf]</a> 
  <a href="publications/theses/vargas2012_bsc.bib">[bib]</a> 
  <a href="publications/theses/vargas2012_bsc_slides.pdf" target="_blank">[slides]</a>

# Footer
footer_show_references: true

# Build settings
remote_theme: evargasv/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
