# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Elizabeth Vargas
#title: Research Associate
email: elizabeth.vargas@hw.ac.uk
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a robotics researcher at Heriot-Watt.

  I obtained my PhD from Heriot-Watt.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: News
more_content: | # this will include new lines to allow paragraphs
  *Jan. 2020:* I am one of the organizers of the [Women in Computer Vision Workshop](https://sites.google.com/view/wicvworkshop-eccv2020/).
  *Nov. 2019:* Sucessfully defended my thesis.

# # More Section
# more_title: Timeline
# more_content: | # this will include new lines to allow paragraphs
#   2019 - Present: Research Associate at ORCAHub.

# more_title: Publications
# more_content: | # this will include new lines to allow paragraphs
#   *Conferences*

#   *Theses*

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
