# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Elizabeth Vargas
title: Research Associate
#institute: Institute of Signals, Sensors and Systems
university: Heriot-Watt University
country: Edinburgh, United Kingdom
office: EM G.06
email: elizabeth.vargas@hw.ac.uk
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: elizavargasv
#github_username:  evargasv
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
#linkedin_username: evargasv
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently a Research Associate at [ORCA Hub](https://orcahub.org/) working on computer vision for underwater robots. I obtained my PhD in Signal Processing from 
  [Heriot-Watt University](https://www.hw.ac.uk/schools/engineering-physical-sciences/institutes/sensors-signals-systems.htm) and my Master's degree in Computer Vision and Robotics via an Erasmus Mundus 
  Master Programme called [VIBOT](https://www.vibot.org/), awarded by the *University of Burgundy*, *University of Girona* and *Heriot-Watt University*. I received my 
  Bachelor's degree in computer science from [Universidad del Valle](http://eisc.univalle.edu.co/index.php/laboratorios/mmv-lab). During my studies, I have also spent time as a research intern at 
  [Toshiba Medical Visualization Systems](https://research.eu.medical.canon/) and [Philips Research Aachen](https://www.philips.com/a-w/research/locations/aachen.html), and participated in an 
  Innovation Think Tank organised by [Siemens Healthcare](https://www.siemens-healthineers.com/en-uk/careers/innovation-think-tank).

  [LinkedIn](https://www.linkedin.com/in/evargasv/) / [Google Scholar](https://scholar.google.com/citations?user=SyDXC-MAAAAJ&hl=en) / 
  [Github](https://github.com/evargasv) / [Twitter](https://twitter.com/elizavargasv) / [CV](cv/vargas_cv.pdf)

# News Section
more_title: News
more_content: | # this will include new lines to allow paragraphs
  - **Feb. 2020:** I am one of the organisers of the [Women in Computer Vision Workshop](https://sites.google.com/view/wicvworkshop-eccv2020/) to be held in conjunction with [ECCV 2020](https://eccv2020.eu/) 
  in Glasgow, United Kingdom.
  - **Jan. 2020:** Our abstract *Smart Underwater Vision: Image Enhancement for Underwater 3D Mapping in the Challenging Environment* was accepted to [OCEANS](https://singapore20.oceansconference.org/).
  - **Nov. 2019:** I defended my PhD thesis, titled [Acoustic Source Localisation in Constrained Environments](publications/theses/vargas2020_phd.pdf). Examiners: [Abderrahim Halimi](https://sites.google.com/site/abderrahimhalimi/) (Heriot-Watt University) 
  and [Keith Holland](https://www.southampton.ac.uk/engineering/about/staff/krh.page) (University of Southampton). Slides [here](publications/theses/vargas2020_phd_slides.pdf).
  - **Oct. 2019:** I participated in the third [ORCA Hub](https://orcahub.org/) demonstrations. Press release [here](https://orcahub.org/articles/a-summary-of-the-blyth-capability-demonstrations).
  - **Jan. 2019:** I joined [ORCA Hub](https://orcahub.org/) as a Research Associate.

# Timeline Section
experience_title: Timeline
experience_content: | # this will include new lines to allow paragraphs

  - **2019-Present:** <font color="#2F4F4F"><b>Research Associate.</b></font> [ORCA Hub](https://orcahub.org/).
  - **2015-2019:** <font color="#2F4F4F"><b>PhD Signal Processing.</b></font> [Heriot-Watt University](https://www.hw.ac.uk/schools/engineering-physical-sciences/institutes/sensors-signals-systems.htm). Advisors: 
  [Keith Brown](https://researchportal.hw.ac.uk/en/persons/keith-edgar-brown) and [Kartic Subr](http://homepages.inf.ed.ac.uk/ksubr/).  
  - **2013-2015:** <font color="#2F4F4F"><b>MSc Computer Vision and Robotics.</b></font> Erasmus Mundus Masters in VIsion and roBOTics [(VIBOT)](https://www.vibot.org/). Advisor: 
  [Keith Goatman](https://www.linkedin.com/in/keith-goatman-6a9ab395/?originalSubdomain=uk).
  - **Summer 2015:** <font color="#2F4F4F"><b>Research Intern.</b></font> [Toshiba Medical Visualization Systems](https://research.eu.medical.canon/). Advisor: [Corne Hoogendoorn](https://scholar.google.com/citations?hl=en&user=F3t43XcAAAAJ&view_op=list_works&sortby=pubdate).
  - **2012-2013:** <font color="#2F4F4F"><b>Project Engineer.</b></font> [IVU Traffic Technologies](https://www.ivu.com/).
  - **2006-2012:** <font color="#2F4F4F"><b>BSc Computer Science.</b></font> [Universidad del Valle](http://eisc.univalle.edu.co/index.php/laboratorios/mmv-lab). Advisor: 
  [Maria Trujillo](http://eisc.univalle.edu.co/index.php/la-escuela/profesores/maria-patricia-trujillo-uribe).
  - **Spring 2012:** <font color="#2F4F4F"><b>Innovation Think Tank Participant.</b></font> [Siemens Healthcare](https://www.siemens-healthineers.com/en-uk/careers/innovation-think-tank).
  - **Spring 2011:** <font color="#2F4F4F"><b>Research Intern.</b></font> [Philips Research Aachen](https://www.philips.com/a-w/research/locations/aachen.html). Advisor: [Martin Weibrecht](https://www.linkedin.com/in/martin-weibrecht-8b133723/).
  - **2010-2011:** <font color="#2F4F4F"><b>BSc Exchange Student.</b></font> [Friedrich-Alexander-Universitat Erlangen-Nurnberg](https://www.fau.eu/). 

# Publications Section
projects_title: Publications
projects_content: | # this will include new lines to allow paragraphs

  <font size="10"><b>Conferences</b></font>

  - **E. Vargas**, J. R. Hopgood, K. Brown, K. Subr, *A Compressed Encoding Scheme for 
  Approximate TDOA Estimation*, in European Signal Processing Conference **(EUSIPCO)**, 
  Rome, Italy, September 2018. 
  <span style="background-color:#CCEC00"><b>Oral Presentation</b></span>
  <a href="publications/conferences/vargas2018_eusipco.pdf">[pdf]</a>
  <a href="publications/conferences/vargas2018_eusipco.bib">[bib]</a>
  <a href="publications/conferences/vargas2018_eusipco_slides.pdf">[slides]</a>

  - **E. Vargas**, K. Brown, K. Subr, *Impact of Microphone Array Configurations on Robust 
  Indirect 3D Acoustic Source Localization*, in International Conference on Acoustics, 
  Speech and Signal Processing **(ICASSP)**, Calgary, Canada, April 2018. 
  <span style="background-color:#CCEC00"><b>Oral Presentation</b></span>
  <a href="publications/conferences/vargas2018_icassp.pdf">[pdf]</a> 
  <a href="publications/conferences/vargas2018_icassp.bib">[bib]</a>
  <a href="publications/conferences/vargas2018_icassp_slides.pdf">[slides]</a> 

  - C. Bustos, **E. Vargas**, M. Trujillo, *Classifying Estimated Stereo Correspondences 
  based on Delaunay Triangulation*, in IberoAmerican Congress on Pattern Recognition 
  **(CIARP)**, Lima, Peru, November 2016.
  <a href="publications/conferences/bustos2016_ciarp.pdf">[pdf]</a> 
  <a href="publications/conferences/bustos2016_ciarp.bib">[bib]</a>

  - **E. Vargas**, M. Trujillo, *A Corresponding Points Classification Approach by Delaunay 
  Triangulation*, in Latin American Conference on Networked and Electronic Media 
  **(LACNEM)**, Santiago, Chile, October 2012.
  <a href="publications/conferences/vargas2012_lacnem.pdf">[pdf]</a> 
  <a href="publications/conferences/vargas2012_lacnem.bib">[bib]</a>

  **Theses**

  - **E. Vargas**, *Acoustic Source Localisation in Constrained Environments*, PhD Thesis, 
  Heriot-Watt University, Edinburgh, United Kingdom, February 2020. 
  <a href="publications/theses/vargas2020_phd.pdf">[pdf]</a> 
  <a href="publications/theses/vargas2020_phd.bib">[bib]</a> 
  <a href="publications/theses/vargas2020_phd_slides.pdf">[slides]</a> 

  - **E. Vargas**, *Texture Enhanced Tissue Analysis*, MSc Thesis, Erasmus Mundus Masters in 
  VIsion and roBOTics (VIBOT), Edinburgh, United Kingdom, June 2015.
  <a href="publications/theses/vargas2015_msc.pdf">[pdf]</a> 
  <a href="publications/theses/vargas2015_msc.bib">[bib]</a> 
  <a href="publications/theses/vargas2015_msc_slides.pdf">[slides]</a>

  - **E. Vargas**, *Classifying Estimated Corresponding Points by Delaunay Triangulation*, 
  BSc Thesis, Universidad del Valle, Cali, Colombia, June 2012.
  <a href="publications/theses/vargas2012_bsc.pdf">[pdf]</a> 
  <a href="publications/theses/vargas2012_bsc.bib">[bib]</a> 
  <a href="publications/theses/vargas2012_bsc_slides.pdf">[slides]</a>

# Footer
footer_show_references: true

# Build settings
remote_theme: evargasv/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
